version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt
  build:
    commands:
      - echo "Running database migrations..."
      - cd Architectural-design-web/archi_designs/manage.py
      - python manage.py migrate
      - echo "Running tests..."
      - python manage.py test
  post_build:
    commands:
      - echo "Deploying to Elastic Beanstalk..."
      - eb use Djangoweb
      - eb deploy