version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt
  build:
    commands:
      - echo "Running database migrations..."
      - python manage.py migrate
      - echo "Running tests..."
      - python manage.py test
  post_build:
    commands:
      - echo "Deploying to Elastic Beanstalk..."
      - eb use Django-web
      - eb deploy