# Generated by Django 4.1.7 on 2023-03-14 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('min_bedrooms', models.IntegerField()),
                ('max_bedrooms', models.IntegerField()),
                ('floors', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=10)),
                ('min_bathrooms', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('max_bathrooms', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('heated_sq_feet', models.DecimalField(blank=True, decimal_places=1, max_digits=20, null=True)),
                ('basement', models.BooleanField(default=False)),
                ('loft', models.BooleanField(default=False)),
                ('walk_in_pantry', models.BooleanField(default=False)),
                ('home_office', models.BooleanField(default=False)),
                ('mudroom', models.BooleanField(default=False)),
                ('bonus_room', models.BooleanField(default=False)),
                ('wrap_around_porch', models.BooleanField(default=False)),
                ('affiliate_link', models.URLField()),
                ('style', models.CharField(choices=[('barndominium', 'Barndominium')], default='barndominium', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='PlanPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='plan_pictures')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_pictures', to='main_designs.plan')),
            ],
        ),
        migrations.CreateModel(
            name='FloorPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_number', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='floor_pictures')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floor_pictures', to='main_designs.plan')),
            ],
        ),
    ]
