# Generated by Django 4.1.7 on 2023-03-14 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_designs', '0002_alter_plan_max_bedrooms_alter_plan_min_bedrooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='heated_sq_feet',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True),
        ),
    ]
